require:
  - rubocop-rspec
  - rubocop-performance
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 110
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Max: 2
