require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  RSpec:
    Patterns:
    - 'spec/meander/.+.rb$'
    - 'spec/shared/.+.rb$'
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 110
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
RSpec/ExampleLength:
  Max: 10
